# Generated by Django 3.0.7 on 2020-08-05 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Images/')),
                ('description', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('postfix', models.CharField(default='png', max_length=5)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('depth', models.DecimalField(decimal_places=1, max_digits=4)),
                ('tumor_stage', models.CharField(choices=[('UC', 'Unconfirmed'), ('T1', 'Tier1'), ('T2', 'Tier2'), ('T3', 'Tier3'), ('T4A', 'Tier4A'), ('T4B', 'Tier4B')], default='UC', max_length=3)),
                ('comment', models.CharField(choices=[('UC', 'Unconfirmed'), ('AP', 'Approved'), ('UA', 'Unaccepted')], default='UC', max_length=2)),
                ('Is_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Masks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('keypoint_x0', models.IntegerField(default=0)),
                ('keypoint_y0', models.IntegerField(default=0)),
                ('keypoint_x1', models.IntegerField(default=100)),
                ('keypoint_y1', models.IntegerField(default=100)),
                ('keypoint_xt', models.IntegerField(default=20)),
                ('keypoint_yt', models.IntegerField(default=20)),
                ('keypoint_xf', models.IntegerField(default=50)),
                ('keypoint_yf', models.IntegerField(default=50)),
                ('dia_x0', models.IntegerField(default=0)),
                ('dia_y0', models.IntegerField(default=0)),
                ('dia_x1', models.IntegerField(default=0)),
                ('dia_y1', models.IntegerField(default=0)),
                ('manual_keypoint', models.BooleanField(default=False)),
                ('related_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v0.Images')),
            ],
        ),
    ]
