# Generated by Django 3.0.7 on 2020-08-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='diameter',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='images',
            name='depth',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
