# Generated by Django 3.0.7 on 2020-08-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0002_auto_20200805_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='depth',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='images',
            name='diameter',
            field=models.FloatField(default=0.0),
        ),
    ]
