# Generated by Django 3.0.7 on 2020-08-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0004_auto_20200810_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='masks',
            name='sacle',
            field=models.FloatField(default=2.08),
        ),
    ]
