# Generated by Django 3.0.7 on 2020-08-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0005_masks_sacle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masks',
            name='sacle',
        ),
        migrations.AddField(
            model_name='masks',
            name='scale',
            field=models.FloatField(default=2.090592),
        ),
    ]
